export default {
  localeTableText: {
    empty: 'Все варианты',
    contains: 'Содержит',
    notContains: 'Не содержит',
    startsWith: 'Начинается с',
    endsWith: 'Заканчивается на',
    equals: 'Совпадает с',
    notEqual: 'Не совпадает с',
    filterOoo: 'Фильтр...',
    andCondition: 'И',
    orCondition: 'Или',
    page: 'Страница',
    to: 'по',
    of: 'из',
    lessThan: 'Меньше',
    greaterThan: 'Больше',
    inRangeStart: 'От',
    inRangeEnd: 'До',
    lessThanOrEqual: 'Меньше или равно',
    greaterThanOrEqual: 'Больше или равно',
    inRange: 'В диапазоне',
    more: '...',
    loadingOoo: 'Загрузка...',
    noRowsToShow: ' ',
    applyFilter: 'Применить',
    resetFilter: 'Сбросить',
    clearFilter: 'Очистить'
  }
}
